# Generated by Django 2.2.2 on 2019-06-21 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='authtoken_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=1900),
            preserve_default=False,
        ),
    ]
